ALTER TABLE "clubs" ADD COLUMN "onboarding_completed_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX "idx_club_members_user" ON "club_members" USING btree ("clerk_user_id");--> statement-breakpoint
CREATE INDEX "idx_club_members_role" ON "club_members" USING btree ("club_id","role");--> statement-breakpoint
CREATE INDEX "idx_rider_profiles_club" ON "rider_profiles" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_rider_profiles_member" ON "rider_profiles" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_rider_profiles_skill" ON "rider_profiles" USING btree ("club_id","skill_level");--> statement-breakpoint
CREATE INDEX "idx_horses_club" ON "horses" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_horses_status" ON "horses" USING btree ("club_id","status");--> statement-breakpoint
CREATE INDEX "idx_horses_skill" ON "horses" USING btree ("club_id","skill_level");--> statement-breakpoint
CREATE INDEX "idx_horses_owner" ON "horses" USING btree ("owner_member_id");--> statement-breakpoint
CREATE INDEX "idx_horses_deleted" ON "horses" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_documents_horse" ON "horse_documents" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_documents_category" ON "horse_documents" USING btree ("horse_id","category");--> statement-breakpoint
CREATE INDEX "idx_exercise_horse" ON "horse_exercise_schedules" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_feed_tracker_club" ON "horse_feed_tracker" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_feed_tracker_empty" ON "horse_feed_tracker" USING btree ("estimated_empty_date");--> statement-breakpoint
CREATE INDEX "idx_feeding_plans_horse" ON "horse_feeding_plans" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_health_records_club" ON "horse_health_records" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_health_records_horse" ON "horse_health_records" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_health_records_type" ON "horse_health_records" USING btree ("horse_id","record_type");--> statement-breakpoint
CREATE INDEX "idx_health_records_next_due" ON "horse_health_records" USING btree ("next_due_date");--> statement-breakpoint
CREATE INDEX "idx_med_logs_medication" ON "horse_medication_logs" USING btree ("medication_id");--> statement-breakpoint
CREATE INDEX "idx_med_logs_date" ON "horse_medication_logs" USING btree ("administered_at");--> statement-breakpoint
CREATE INDEX "idx_medications_horse" ON "horse_medications" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_medications_active" ON "horse_medications" USING btree ("horse_id","is_active");--> statement-breakpoint
CREATE INDEX "idx_arena_schedules" ON "arena_schedules" USING btree ("arena_id","day_of_week");--> statement-breakpoint
CREATE INDEX "idx_arenas_club" ON "arenas" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_slots_club_date" ON "booking_slots" USING btree ("club_id","date");--> statement-breakpoint
CREATE INDEX "idx_slots_coach" ON "booking_slots" USING btree ("coach_member_id","date");--> statement-breakpoint
CREATE INDEX "idx_slots_arena" ON "booking_slots" USING btree ("arena_id","date");--> statement-breakpoint
CREATE INDEX "idx_bookings_club" ON "bookings" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_bookings_rider" ON "bookings" USING btree ("rider_member_id");--> statement-breakpoint
CREATE INDEX "idx_bookings_slot" ON "bookings" USING btree ("slot_id");--> statement-breakpoint
CREATE INDEX "idx_bookings_horse" ON "bookings" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_bookings_status" ON "bookings" USING btree ("club_id","status");--> statement-breakpoint
CREATE INDEX "idx_bookings_date" ON "bookings" USING btree ("club_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_bookings_stripe" ON "bookings" USING btree ("stripe_payment_intent_id");--> statement-breakpoint
CREATE INDEX "idx_pairing_horse_rider" ON "horse_pairing_history" USING btree ("horse_id","rider_member_id");--> statement-breakpoint
CREATE INDEX "idx_lesson_types_club" ON "lesson_types" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_waitlist_slot" ON "waitlist" USING btree ("slot_id","position");--> statement-breakpoint
CREATE INDEX "idx_coupon_usages_coupon" ON "coupon_usages" USING btree ("coupon_id");--> statement-breakpoint
CREATE INDEX "idx_coupon_usages_rider" ON "coupon_usages" USING btree ("coupon_id","rider_member_id");--> statement-breakpoint
CREATE INDEX "idx_coupons_status" ON "coupons" USING btree ("club_id","status");--> statement-breakpoint
CREATE INDEX "idx_packages_club" ON "packages" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_rider_packages_rider" ON "rider_packages" USING btree ("rider_member_id");--> statement-breakpoint
CREATE INDEX "idx_rider_packages_expiry" ON "rider_packages" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_competition_classes_competition" ON "competition_classes" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "idx_competition_entries_rider" ON "competition_entries" USING btree ("rider_member_id");--> statement-breakpoint
CREATE INDEX "idx_competition_results_entry" ON "competition_results" USING btree ("entry_id");--> statement-breakpoint
CREATE INDEX "idx_competitions_club" ON "competitions" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_competitions_date" ON "competitions" USING btree ("club_id","start_date");--> statement-breakpoint
CREATE INDEX "idx_expenses_club" ON "expenses" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_expenses_date" ON "expenses" USING btree ("club_id","date");--> statement-breakpoint
CREATE INDEX "idx_expenses_horse" ON "expenses" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_expenses_category" ON "expenses" USING btree ("club_id","category");--> statement-breakpoint
CREATE INDEX "idx_invoices_club" ON "invoices" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_invoices_member" ON "invoices" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_invoices_status" ON "invoices" USING btree ("club_id","status");--> statement-breakpoint
CREATE INDEX "idx_livery_club" ON "livery_contracts" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_livery_owner" ON "livery_contracts" USING btree ("owner_member_id");--> statement-breakpoint
CREATE INDEX "idx_livery_horse" ON "livery_contracts" USING btree ("horse_id");--> statement-breakpoint
CREATE INDEX "idx_payments_club" ON "payments" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_payments_member" ON "payments" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_payments_status" ON "payments" USING btree ("club_id","status");--> statement-breakpoint
CREATE INDEX "idx_payments_stripe" ON "payments" USING btree ("stripe_payment_intent_id");--> statement-breakpoint
CREATE INDEX "idx_payments_date" ON "payments" USING btree ("club_id","paid_at");--> statement-breakpoint
CREATE INDEX "idx_audit_club" ON "audit_log" USING btree ("club_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_actor" ON "audit_log" USING btree ("actor_member_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_resource" ON "audit_log" USING btree ("resource_type","resource_id");--> statement-breakpoint
CREATE INDEX "idx_comments_post" ON "community_comments" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX "idx_comments_parent" ON "community_comments" USING btree ("parent_comment_id");--> statement-breakpoint
CREATE INDEX "idx_posts_topic_created" ON "community_posts" USING btree ("topic_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_posts_author" ON "community_posts" USING btree ("author_member_id");--> statement-breakpoint
CREATE INDEX "idx_topics_club" ON "community_topics" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "idx_groom_tasks_date" ON "groom_tasks" USING btree ("club_id","scheduled_date");--> statement-breakpoint
CREATE INDEX "idx_groom_tasks_assigned" ON "groom_tasks" USING btree ("assigned_to_member_id","scheduled_date");--> statement-breakpoint
CREATE INDEX "idx_groom_tasks_horse" ON "groom_tasks" USING btree ("horse_id","scheduled_date");--> statement-breakpoint
CREATE INDEX "idx_notifications_recipient" ON "notifications" USING btree ("recipient_member_id","is_read");--> statement-breakpoint
CREATE INDEX "idx_notifications_date" ON "notifications" USING btree ("recipient_member_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_achievements_rider" ON "rider_achievements" USING btree ("rider_member_id");